const ORDERS_PAGE_LAYOUT = {
    TIMETABLE: 'TIMETABLE',
    TIMETABLE_GROUPED_BY_MENU: 'TIMETABLE_GROUPED_BY_MENU',
    LIST: 'LIST',
    DEFAULT: 'TIMETABLE'
}

export default Object.freeze(ORDERS_PAGE_LAYOUT);
